- name: Checkout private repo remotely
  uses: actions/checkout@v2
  with:
    repository: explicitworkload/SFAHiddenRepository
    #path: <folder of choice>
    token: ${{ secrets.REMOTE_TOKEN }}
- name: Show hidden files
  run: |
    ls
